#!/bin/bash
set -e

default_sink=$(pactl info | grep "Default Sink:" | cut '-d ' -f3)
sinks=$(pactl list short sinks | cut -f2 | grep -v 'easyeffects')

# for wrap-around
sinks="$sinks
$sinks"

next_sink=$(echo "$sinks" | awk "/$default_sink/{getline x;print x;exit;}")

function get_device_name() {
    device_name=$(pactl list sinks | awk -v device="$next_sink" '
    /node.name =/ {node_name=$0}
    /device.description =/ {description=$0}
    
    # Skip the easyeffects_sink
    node_name != "node.name = easyeffects_sink" && node_name {
        # If node_name matches the requested device, print the description
        if (node_name ~ "node.name = \"" device "\"") {
            # Clean the description and print it
            gsub(/"/, "", description)
            print substr(description, index(description, "=") + 2)
            exit
        }
    }
    ')
}

function show_active_device() {
    get_device_name
    dunstify -t 1000 -r 46001 -u normal "$device_name"
}

pactl set-default-sink "$next_sink"
pactl list short sink-inputs |
    cut -f1 |
    xargs -I{} pactl move-sink-input {} "$next_sink"

show_active_device
