name: Secret Scanning

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      # - name: Gitleaks Scan
      #   uses: gitleaks/gitleaks-action@v2.3.4

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.82.12
    